config/routes.rb
Rails.application.routes.draw do
  get "users/show"
  get "rooms/index"
  get "exchange_diaries/index"

  devise_for :users, only: :omniauth_callbacks, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  scope "(:locale)", locale: /en|ja/ do
    devise_for :users, skip: :omniauth_callbacks, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
    }

    resource :user, only: %i[show]
    get "top/index"
    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
    resources :rooms, only: %i[index show create] do
      resources :exchange_diaries, only: %i[index create update destroy] do
        resource :read, only: %i[create destroy]
      end
      resources :whiteboards, only: %i[create update]
      resources :state_calendars, only: %i[new create index show update edit destroy]
      resources :invitation_tokens, only: %i[create index update]
      resources :greetings, only: %i[new create index edit update destroy]
      resources :spots, only: %i[index new create show edit update destroy] do
        resources :comments, only: %i[create update destroy]
      end
      resources :calendars, only: %i[index new create show edit update destroy] do
        collection do
          get :import
          post :import
        end
      end
    end

    resources :areas, only: %i[create update index]
    resources :weather_records, only: %i[create update]
    resources :posts, only: %i[new create index edit show update destroy] do
      resources :answers, only: %i[create edit destroy], shallow: true
    end
    resources :roommate_lists, only: %i[] do
      collection do
        get "join"  # /roommate_lists/join?token=xxx
      end
    end

    # Defines the root path route ("/")
    root "top#index"
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get "terms", to: "pages#terms", as: :terms
  get "privacy", to: "pages#privacy", as: :privacy
  get "contact", to: "pages#contact", as: :contact

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/models/greeting.rb
class Greeting < ApplicationRecord
  belongs_to :user
  belongs_to :room

  enum greeting_type: { welcome: 0, return: 1 }

  validates :greeting_type, presence: true
  validates :message, presence: true
end

app/controllers/greetings_controller.rb
class GreetingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_room
  def index
    @room = Room.find(params[:room_id])
    @greetings = @room.greetings.includes(:user).order(created_at: :desc)
    @welcome = @greetings.welcome.where(user: current_user)
    @return = @greetings.return.where(user: current_user)
    @roommates_except_self = current_user.roommates_except_self(@room)
  end

  def new
    @room = Room.find(params[:room_id])
    @greeting = @room.greetings.new
  end

  def create
    @room = Room.find(params[:room_id])
    @greeting = @room.greetings.new(greeting_params)
    @greeting.user = current_user

    if @greeting.save
        redirect_to room_greetings_path(@room), notice: t("flash.greeting.save")
    else
        flash.now[:alert] = t("flash.greeting.failed_save")
        render :new, status: :unprocessable_entity
    end
  end

  def update
    @room = Room.find(params[:room_id])
    @greeting = @room.greetings.find_by(user: current_user, id: params[:id])

    if @greeting.update(greeting_params)
      redirect_to room_greetings_path(@room), notice: t("flash.greeting.update")
    else
      @greetings = @room.greetings.includes(:user).order(created_at: :desc)
      flash.now[:alert] = t("flash.greeting.failed_update")
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @room = Room.find(params[:room_id])
    @greeting = @room.greetings.find_by(user: current_user, id: params[:id])
  end

  def destroy
    @room = Room.find(params[:room_id])
    @greeting = @room.greetings.find_by(user: current_user, id: params[:id])

    if @greeting.destroy
      redirect_to room_greetings_path(@room), notice: t("flash.greeting.delete")
    else
      @greetings = @room.greetings.includes(:user).order(created_at: :desc)
      flash.now[:alert] = t("flash.greeting.failed_delete")
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_room
    @room = Room.find_by(id: params[:room_id])
    unless @room && (@room.user_id == current_user.id || RoommateList.exists?(user_id: current_user.id, room_id: @room.id))
      redirect_to root_path, alert: t("flash.room.failed_find")
    end
  end

  def greeting_params
    params.require(:greeting).permit(:message, :greeting_type, :room_id, :user_id)
  end
end

app/helpers/greetings_helper.rb
module GreetingsHelper
end

app/views/greetings/edit.html.erb
<%= form_with model: [@room, @greeting], local: true, class: "max-w-md mx-auto p-6 bg-light-gray/50 rounded-2xl shadow-lg mt-2" do |f| %>
  <% if @greeting.errors.any? %>
    <div class= "text-bold text-brown">
      <ul class="list-disc pl-5">
        <% @greeting.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
    <%= f.label :greeting_type, t("views.greeting.status"), class: "text-dark-gray" %>
    <%= f.select :greeting_type,
        [[t("views.greeting.welcome_message"), "welcome"], [t("views.greeting.return_message"), "return"]],
        { prompt: t("views.greeting.select") }, class: "bg-matcha/65 text-beige py-2 pl-3 pr-10 rounded w-full focus:ring-2 focus:ring-matcha" %>

    <%= f.label :message, t("views.greeting.message"), class: "text-dark-gray" %>
    <%= f.text_field :message, placeholder: t("views.greeting.enter"), class: "w-full px-4 py-2 bg-light-gray/75 text-matcha rounded-lg focus:outline-none focus:ring-2 focus:ring-matcha" %>
    <div class="text-center">
      <%= f.submit t("buttons.update"), class: "bg-blue/75 text-dark-gray py-2 px-6 rounded hover:bg-blue/30 transition duration-200 mt-2", data: { turbo: false } %>
      <%= link_to '<i class="fa-solid fa-trash text-lg text-blue"></i>'.html_safe, room_greeting_path(@room, @greeting), data: { turbo_method: :delete, turbo_confirm: t("flash.alert") } %>
    </div>
<% end %>

<%= link_to t("views.greeting.back"), room_greetings_path(@room), class: "bg-light-gray/75 py-2 px-6 rounded shadow mb-4 hover:bg-light-gray/50 transition text-dark-gray" %>

app/views/greetings/index.html.erb
<h1 class="text-dark-gray font-bold"><%= t("views.greeting.greeting_setting", user: current_user.name, room: @room.name) %></h1>
<%= link_to t("buttons.new"), new_room_greeting_path(), class: "bg-blue/75 p-4 rounded shadow mb-4 mt-2 hover:bg-blue-30 transition text-dark-gray" %>
<div class="w-full max-w-md mx-auto bg-light-gray/40 p-6 rounded-lg shadow-lg mt-4">
    <% if @return.present? %>
        <h2 class="text-matcha font-bold"><%= t("views.greeting.return_message") %></h2>
        <% @greetings.return.each do |greeting| %>
            <% if greeting.user == current_user %>
            <div class="flex text-dark-gray">
                <%= l(greeting.created_at, format: :short) %>
                <h1 class = "text-matcha">「<%= link_to greeting.message, edit_room_greeting_path(@room, greeting) %>」</h1>
            </div>
            <% end %>
        <% end %>
    <% else %>
        <h2 class="text-gray"><%= t("views.greeting.none_return") %></h2>
    <% end %>
</div>

<div class="w-full max-w-md mx-auto bg-light-gray/40 p-6 rounded-lg shadow-lg mt-4">
    <% if @welcome.present? %>
        <h2 class="text-matcha font-bold"><%= t("views.greeting.welcome_message") %></h2>
        <% @greetings.welcome.each do |greeting| %>
          <% if greeting.user == current_user %>
            <div class="flex text-dark-gray">
                <%= l(greeting.created_at, format: :short) %>
                <h1 class = "text-matcha">「<%= link_to greeting.message, edit_room_greeting_path(@room, greeting) %>」</h1>
            </div>
          <% end %>
        <% end %>
    <% else %>
        <h2 class="text-gray"><%= t("views.greeting.none_welcome") %></h2>
    <% end %>
</div>
<%= link_to t("views.room.back_to_room", room_name: @room.name), room_path(@room), class: "bg-brown/30 p-2 rounded shadow mb-2 mt-4 text-brown font-bold hover:bg-brown/70 transition", data: { turbo: false } %>

app/views/greetings/new.html.erb
<div class="mb-6">
  <div class="text-dark-gray">
    <h1><%= t("views.greeting.note1") %></h1>
    <h1><%= t("views.greeting.note2") %></h1>
  </div>
    <%= form_with model: [@room, @greeting], local: true, class: "max-w-md mx-auto p-6 bg-light-gray/50 rounded-2xl shadow-lg mt-2" do |f| %>
      <% if @greeting.errors.any? %>
        <div class= "bg-beige/30 text-matcha/75 font-bold">
          <ul class="list-disc pl-5">
            <% @greeting.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <%= f.label :greeting_type, t("views.greeting.status"), class: "text-dark-gray" %>
      <%= f.select :greeting_type,
          [[t("views.greeting.welcome_message"), "welcome"], [t("views.greeting.return_message"), "return"]],
          { prompt: t("views.greeting.select") }, class: "bg-matcha/65 text-beige py-2 pl-3 pr-10 rounded w-full focus:ring-2 focus:ring-matcha" %>

      <%= f.label :message, t("views.greeting.message"), class: "text-dark-gray" %>
      <%= f.text_field :message, placeholder: t("views.greeting.enter"), class: "w-full px-4 py-2 bg-light-gray/75 text-matcha rounded-lg focus:outline-none focus:ring-2 focus:ring-matcha" %>
      <div class="text-center">
        <%= f.submit t("buttons.save"), class: "bg-blue/75 text-dark-gray py-2 px-6 rounded hover:bg-blue/30 transition duration-200 mt-2", data: { turbo: false } %>
      </div>
    <% end %>
  </div>
</div>

<%= link_to t("views.greeting.back"), room_greetings_path(@room), class: "bg-light-gray/75 py-2 px-6 rounded shadow mb-4 hover:bg-light-gray/50 transition text-dark-gray" %>