config/routes.rb
Rails.application.routes.draw do
  get "users/show"
  get "rooms/index"
  get "exchange_diaries/index"

  devise_for :users, only: :omniauth_callbacks, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  scope "(:locale)", locale: /en|ja/ do
    devise_for :users, skip: :omniauth_callbacks, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
    }

    resource :user, only: %i[show]
    get "top/index"
    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
    resources :rooms, only: %i[index show create] do
      resources :exchange_diaries, only: %i[index create update destroy] do
        resource :read, only: %i[create destroy]
      end
      resources :whiteboards, only: %i[create update]
      resources :state_calendars, only: %i[new create index show update edit destroy]
      resources :invitation_tokens, only: %i[create index update]
      resources :greetings, only: %i[new create index edit update destroy]
      resources :spots, only: %i[index new create show edit update destroy] do
        resources :comments, only: %i[create update destroy]
      end
      resources :calendars, only: %i[index new create show edit update destroy] do
        collection do
          get :import
          post :import
        end
      end
    end

    resources :areas, only: %i[create update index]
    resources :weather_records, only: %i[create update]
    resources :posts, only: %i[new create index edit show update destroy] do
      resources :answers, only: %i[create edit destroy], shallow: true
    end
    resources :roommate_lists, only: %i[] do
      collection do
        get "join"  # /roommate_lists/join?token=xxx
      end
    end

    # Defines the root path route ("/")
    root "top#index"
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get "terms", to: "pages#terms", as: :terms
  get "privacy", to: "pages#privacy", as: :privacy
  get "contact", to: "pages#contact", as: :contact

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/views/shared/_before_login_header.html.erb
<header>
  <nav class="bg-yellow/30 text-matcha text-sm md:text-lg font-semibold fixed top-0 w-full z-50">
    <div class="max-w-screen-xl flex items-center justify-between mx-auto p-2 md:p-4">
      <!-- ロゴ -->
      <div class="text-md md:text-2xl">
        <%= link_to "Online Room", root_path, data: { turbo: false } %>
      </div>
      <div class="underline">
        <%= link_to('JA', locale: 'ja', class: "block") %> /
        <%= link_to('EN', locale: 'en', class: "block") %>
      </div>

      <!-- ハンバーガーボタン（モバイルのみ） -->
      <button id="menu-toggle" class="md:hidden text-2xl focus:outline-none">
        ☰
      </button>

      <!-- PC用メニュー（横並び・常時表示） -->
      <div class="hidden md:flex md:items-center md:space-x-6">
        <div class="underline">
          <%= link_to "Tips", posts_path, data: { turbo: false } %>
        </div>
        <div class="flex space-x-4 underline items-center">
          <%= link_to t('devise.sessions.new.sign_in'), new_user_session_path, data: { turbo: false } %>
          <%= link_to t('devise.registrations.sign_up'), new_user_registration_path, data: { turbo: false } %>
          <%= button_to user_google_oauth2_omniauth_authorize_path(locale: nil), class: 'btn flex items-center space-x-2', data: { turbo: false } do %>
            <img src="/google_logo.svg" alt="Sign in with Google" width="200" /><br>
          <% end %>
        </div>
      </div>
    </div>

    <!-- モバイル用スライドメニュー -->
    <div id="side-menu" class="fixed top-0 right-0 h-full w-auto max-w-xs bg-white text-matcha shadow-lg transform translate-x-full transition-transform duration-300 z-50 md:hidden">
      <!-- 閉じるボタン -->
      <div class="flex justify-end p-4">
        <button id="close-menu" class="text-2xl">✕</button>
      </div>
      <!-- メニュー内容 -->
      <div class="flex flex-col space-y-6 px-6 text-lg">
        <div class="underline">
          <%= link_to "Tips", posts_path, data: { turbo: false }, class: "block" %>
        </div>
        <div class="flex flex-col space-y-4 underline">
          <%= link_to t('devise.sessions.new.sign_in'), new_user_session_path, data: { turbo: false }, class: "block" %>
          <%= link_to t('devise.registrations.sign_up'), new_user_registration_path, data: { turbo: false }, class: "block" %>
          <%= button_to user_google_oauth2_omniauth_authorize_path(locale: nil), class: 'btn flex items-center space-x-2 w-full justify-center', data: { turbo: false } do %>
            <img src="/google_logo.svg" alt="Sign in with Google" width="200" />
          <% end %>
        </div>
      </div>
    </div>
  </nav>

  <!-- JS：ハンバーガーメニューの開閉 -->
  <script>
    document.addEventListener("turbo:load", () => {
      const menu = document.getElementById("side-menu");
      const openBtn = document.getElementById("menu-toggle");
      const closeBtn = document.getElementById("close-menu");

      openBtn.addEventListener("click", () => {
        menu.classList.remove("translate-x-full");
        menu.classList.add("translate-x-0");
      });

      closeBtn.addEventListener("click", () => {
        menu.classList.add("translate-x-full");
        menu.classList.remove("translate-x-0");
      });
    });
  </script>
</header>

app/views/shared/_footer.html.erb
<footer class="bg-yellow/30 text-matcha text-xs md:text-lg font-semibold w-full z-50">
  <div class="max-w-screen-lg mx-auto">
    <div class="flex justify-between items-center p-2">
      <div class="flex space-x-4">
          <%= link_to t("views.footer.contact"), contact_path %>
          <%= link_to t("views.footer.terms_of_service"), terms_path %>
          <%= link_to t("views.footer.privacy_policy").html_safe, privacy_path %>
      </div>
      <div class="flex flex-col justify-end text-gray">
          <i class="fa-brands fa-x-twitter"></i>
          <p>@Online Room</p>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <nav class="bg-yellow/30 text-matcha text-sm md:text-lg font-semibold fixed top-0 w-full z-50">
    <div class="max-w-screen-xl flex items-center justify-between mx-auto p-2 md:p-4">
      <!-- ロゴ -->
      <div class="text-md md:text-2xl">
        <%= link_to "Online Room", root_path, data: { turbo: false } %>
      </div>
      <div class="underline">
        <%= link_to('JA', locale: 'ja', class: "block") %> /
        <%= link_to('EN', locale: 'en', class: "block") %>
      </div>

      <button id="menu-toggle" class="md:hidden text-2xl focus:outline-none">
        ☰
      </button>

      <!-- PC用メニュー -->
      <div class="hidden md:flex md:flex-row md:items-center md:space-x-4 text-sm md:text-lg">
        <div class="underline">
          <%= link_to "Tips", posts_path, data: { turbo: false }, class: "confirm-on-leave" %>
        </div>
        <div class="underline">
          <%= link_to t('views.room.front_door'), rooms_path, data: { turbo: false }, class: "confirm-on-leave" %>
        </div>
        <div class="underline">
          <%= link_to t('devise.sessions.signed_out_button'), destroy_user_session_path, method: :delete, data: { turbo: false } %>
        </div>
        <div class="underline">
          <%= link_to "#{current_user.name} さん", user_path, class: "btn" %>
        </div>
      </div>
    </div>

    <!-- モバイル用スライドメニュー -->
    <div id="side-menu" class="fixed top-0 right-0 h-full w-auto max-w-xs bg-white text-matcha shadow-lg transform translate-x-full transition-transform duration-300 z-60 md:hidden">
      <div class="flex justify-end p-4">
        <button id="close-menu" class="text-2xl">✕</button>
      </div>
      <div class="flex flex-col space-y-4 px-6 text-lg underline">
        <%= link_to "Tips", posts_path, data: { turbo: false }, class: "confirm-on-leave" %>
        <%= link_to t('views.room.front_door'), rooms_path, data: { turbo: false }, class: "confirm-on-leave" %>
        <%= link_to t('devise.sessions.signed_out_button'), destroy_user_session_path, method: :delete, data: { turbo: false } %>
        <%= link_to "#{current_user.name} さん", user_path %>
      </div>
    </div>
  </nav>

  <script>
    document.addEventListener("turbo:load", function () {
      const menu = document.getElementById("side-menu");
      const openBtn = document.getElementById("menu-toggle");
      const closeBtn = document.getElementById("close-menu");
      const leaveMessage = document.querySelector("meta[name='leave-room-message']").content;

      openBtn?.addEventListener("click", () => {
        menu.classList.remove("translate-x-full");
        menu.classList.add("translate-x-0");
      });

      closeBtn?.addEventListener("click", () => {
        menu.classList.add("translate-x-full");
        menu.classList.remove("translate-x-0");
      });

      const links = document.querySelectorAll(".confirm-on-leave");
      links.forEach(link => {
        link.addEventListener("click", function (event) {
          const currentPath = window.location.pathname;
          const showPageRegex = /^(\/[a-z]{2})?\/rooms\/.+$/;
          if (showPageRegex.test(currentPath)) {
            const confirmed = confirm(leaveMessage);
            if (!confirmed) {
              event.preventDefault();
            }
          }
        });
      });
    });
  </script>
</header>