config/routes.rb
Rails.application.routes.draw do
  get "users/show"
  get "rooms/index"
  get "exchange_diaries/index"

  devise_for :users, only: :omniauth_callbacks, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  scope "(:locale)", locale: /en|ja/ do
    devise_for :users, skip: :omniauth_callbacks, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
    }

    resource :user, only: %i[show]
    get "top/index"
    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
    resources :rooms, only: %i[index show create] do
      resources :exchange_diaries, only: %i[index create update destroy] do
        resource :read, only: %i[create destroy]
      end
      resources :whiteboards, only: %i[create update]
      resources :state_calendars, only: %i[new create index show update edit destroy]
      resources :invitation_tokens, only: %i[create index update]
      resources :greetings, only: %i[new create index edit update destroy]
      resources :spots, only: %i[index new create show edit update destroy] do
        resources :comments, only: %i[create update destroy]
      end
      resources :calendars, only: %i[index new create show edit update destroy] do
        collection do
          get :import
          post :import
        end
      end
    end

    resources :areas, only: %i[create update index]
    resources :weather_records, only: %i[create update]
    resources :posts, only: %i[new create index edit show update destroy] do
      resources :answers, only: %i[create edit destroy], shallow: true
    end
    resources :roommate_lists, only: %i[] do
      collection do
        get "join"  # /roommate_lists/join?token=xxx
      end
    end

    # Defines the root path route ("/")
    root "top#index"
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get "terms", to: "pages#terms", as: :terms
  get "privacy", to: "pages#privacy", as: :privacy
  get "contact", to: "pages#contact", as: :contact

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/models/calendar.rb
class Calendar < ApplicationRecord
  before_validation :adjust_all_day_times

  belongs_to :user
  belongs_to :room

  validates :start_time, presence: true
  validates :end_time, presence: true
  validate :time_rule

  enum schedule_type: { all_day: 0, timed: 1 }
  enum source: { manual: 0, google: 1 }
  enum visibility: { personal: 0, share_only: 1, together: 2 }
  enum category: { relax: 0, work_study: 1, event: 2 }

  validates :schedule_type, presence: true
  validates :visibility, presence: true
  validates :category, presence: true
  validates :name, presence: true

  def display_start_time
    if schedule_type == "all_day"
      start_time.strftime("%Y-%m-%d")
    else
      start_time.strftime("%Y-%m-%d %H:%M")
    end
  end

  def display_end_time
    return nil if schedule_type == "all_day" && start_time.to_date == end_time.to_date

    if schedule_type == "all_day"
      end_time.strftime("%Y-%m-%d")
    else
      end_time.strftime("%Y-%m-%d %H:%M")
    end
  end

  def calendar_date
    start_time.to_date
  end

  def all_day?
    schedule_type == "all_day"
  end

  private

  def adjust_all_day_times
    return unless all_day?

    if start_time.present?
      self.start_time = start_time.beginning_of_day
    end

    if end_time.present?
      self.end_time = end_time.end_of_day
    end
  end

  def time_rule
    return if start_time.blank? || end_time.blank?

    if start_time > end_time
      errors.add(:start_time, I18n.t("flash.calendar.start_time_rule"))
    end
  end
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_room

  def index
    @room = Room.find(params[:room_id])
    @calendars = @room.calendars.includes(:user).order(created_at: :desc)
    @calendar_users = current_user.grouped_shared_users[@room.id] || []
    @today_state = current_user.state_calendars.find_by(room: @room, date: Date.current)

    shared_calendars = @room.calendars.includes(:user).where(visibility: [ :share_only, :together ]).order(created_at: :desc)

    personal_calendars = @room.calendars.includes(:user)
                                    .where(visibility: :personal, user: current_user)
                                    .order(created_at: :desc)

    together_calendars = @room.calendars.includes(:user)
                             .where(visibility: :together)
                             .order(created_at: :desc)

    case params[:visibility]
    when "personal"
      @calendars = personal_calendars
    when "together"
      @calendars = together_calendars
    else
      if params[:category].present? && Calendar.categories.key?(params[:category])
        category_value = Calendar.categories[params[:category]]
        @calendars = shared_calendars.where(category: category_value)
      else
        @calendars = shared_calendars
      end
    end
  end

  def show
    @room = Room.find(params[:room_id])
    @calendar = @room.calendars.includes(:user).find(params[:id])

    if @calendar.visibility == "personal" && @calendar.user != current_user
      redirect_to root_path, alert: t("flash.calendar.unauthorize")
    end
  end

  def new
    @room = Room.find(params[:room_id])
    start_time = (params[:date].presence && Date.parse(params[:date])) || Date.current
    @calendar = current_user.calendars.find_by(room: @room, start_time: start_time) ||
            current_user.calendars.new(room: @room, start_time: start_time)
  end

  def create
    @calendar = current_user.calendars.new(calendar_params)
    @calendar.room = @room

    if @calendar.save
      redirect_to room_calendars_path(@room), notice: t("flash.calendar.save")
    else
      flash.now[:alert] = t("flash.calendar.failed_save")
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @room = Room.find(params[:room_id])
    @calendar = @room.calendars.find(params[:id])
    @calendar_date = params[:date].present? ? Date.parse(params[:date]) : Date.today

    @calendars = @room.calendars
                    .where(user: current_user)
                    .where(start_time: @calendar_date.beginning_of_day..@calendar_date.end_of_day)
  end

  def update
    @room = Room.find(params[:room_id])
    @calendar = @room.calendars.find_by(user: current_user, id: params[:id])

    unless @calendar&.user == current_user
      redirect_to room_calendars_path(@room), alert: t("flash.calendar.unauthorize_update")
    end

    if @calendar.update(calendar_params)
      redirect_to room_calendars_path(@room), notice: t("flash.calendar.update")
    else
      @calendars = @room.calendars.includes(:user).order(created_at: :desc)
      flash.now[:alert] = t("flash.calendar.failed_update")
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @room = Room.find(params[:room_id])
    @calendar = @room.calendars.find_by(user: current_user, id: params[:id])

    unless @calendar&.user == current_user
      redirect_to room_calendars_path(@room), alert: t("flash.calendar.unauthorize_destroy")
    end

    if @calendar.destroy
      redirect_to room_calendars_path(@room), notice: t("flash.calendar.destroy")
    else
      @calendars = @room.calendars.includes(:user).order(created_at: :desc)
      flash.now[:alert] = t("flash.calendar.failed_destroy")
      render :new, status: :unprocessable_entity
    end
  end

  def import
    @room = Room.find(params[:room_id])
    service = CalendarService.new(current_user)
    saved_token = current_user.sync_token
    response = service.fetch_events(sync_token: saved_token)

    events = response.items
    next_sync_token = response.next_sync_token
    google_calendar_id = service.calendar_id

  ActiveRecord::Base.transaction do
    events.each do |event|
      start_time = event.start.date_time || Time.zone.parse(event.start.date.to_s)
      end_time = event.end.date_time || Time.zone.parse(event.end.date.to_s) - 1.second
      schedule_type = event.start.date_time.nil? ? :all_day : :timed

      calendar = current_user.calendars.find_or_initialize_by(google_event_id: event.id, room: @room)
      calendar.assign_attributes(
        name: event.summary || "No Title",
        description: event.description,
        start_time: start_time,
        end_time: end_time,
        schedule_type: schedule_type,
        source: :google,
        visibility: :personal,
        category: :event,
        room: @room,
        google_calendar_id: google_calendar_id,
        google_event_id: event.id,
        last_synced_at: Time.current
      )
      calendar.save!
    end
    current_user.update!(sync_token: response.next_sync_token)
  end
    redirect_to room_calendars_path(@room, visibility: "personal"), notice: t("flash.calendar.input")
  rescue => e
    logger.error "Import failed: #{e.message}"
    flash.now[:alert] = t("flash.calendar.failed_input")
    render :index, status: :unprocessable_entity
  end


  private

  def set_room
    @room = Room.find_by(id: params[:room_id])
    unless @room && (@room.user_id == current_user.id || RoommateList.exists?(user_id: current_user.id, room_id: @room.id))
      redirect_to root_path, alert: t("flash.room.failed_find")
    end
  end

  def calendar_params
    params.require(:calendar).permit(:name, :description, :schedule_type, :start_time, :end_time, :visibility, :category, :source, :user_id, :room_id)
  end
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/views/calendars/_form.html.erb
<div class="schedule-type-selection">
  <%= f.radio_button :schedule_type, "timed", id: "schedule_type_timed", checked: true %>
  <%= f.label :schedule_type_timed, t('views.calendar.add_time') %>

  <%= f.radio_button :schedule_type, "all_day", id: "schedule_type_all_day" %>
  <%= f.label :schedule_type_all_day, t('views.calendar.all_day') %>
</div>

<!-- 終日 -->
<div id="all-day-fields" style="display: none;">
  <div class="form-group">
    <%= f.label :start_time, t('activerecord.attributes.calendar.start_date') %>
    <%= f.date_field :start_time, value: @calendar.start_time&.to_date || Date.current, class: "text-dark-gray bg-matcha/30" %>
  </div>
  <div class="form-group">
    <%= f.label :end_time, t('activerecord.attributes.calendar.end_date') %>
    <%= f.date_field :end_time, value: (
          (f.object.end_time || f.object.start_time || (params[:date].present? ? Date.parse(params[:date]) : Date.today))
          ).to_date.strftime("%Y-%m-%d"), class: "text-dark-gray bg-matcha/30" %>
  </div>
</div>

<!-- 時間指定　-->
<div id="timed-fields">
  <div class="form-group">
    <%= f.label :start_time, t('activerecord.attributes.calendar.start_time') %>
    <%= f.datetime_local_field :start_time, value: @calendar.start_time&.to_date || Date.current, class: "text-dark-gray bg-matcha/30" %>
  </div>
  <div class="form-group">
    <%= f.label :end_time, t('activerecord.attributes.calendar.end_time') %>
    <%= f.datetime_local_field :end_time, value: (
          (f.object.end_time ||
           (f.object.start_time ? f.object.start_time + 30.minutes : nil) ||
           (params[:datetime].present? ? Date.parse(params[:datetime]) : Time.current + 30.minutes))
          ).strftime("%Y-%m-%dT%H:%M"), class: "text-dark-gray bg-matcha/30" %>
  </div>
</div>
<div>
  <%= f.label :name, t('activerecord.attributes.calendar.name') %>
  <%= f.text_field :name, placeholder: t("views.calendar.enter"), class: "w-full px-4 py-2 bg-light-gray/75 text-matcha rounded-lg focus:outline-none focus:ring-2 focus:ring-matcha" %>

  <%= f.label :source, t('activerecord.attributes.calendar.source'), class: "text-dark-gray" %>
  <%= f.select :source,
    [[t('views.calendar.google'), "google"], [t('views.calendar.manual'), "manual"]],
    { prompt: t('views.calendar.select') }, class: "bg-matcha/65 text-beige py-2 pl-3 pr-10 rounded w-full focus:ring-2 focus:ring-matcha"
  %>

  <%= f.label :description, t('activerecord.attributes.calendar.description'), class: "text-dark-gray" %>
  <%= f.text_field :description, placeholder: t("views.calendar.add_note"), class: "w-full px-4 py-2 bg-light-gray/75 text-matcha rounded-lg focus:outline-none focus:ring-2 focus:ring-matcha" %>

  <%= f.label :category, t('activerecord.attributes.calendar.category'), class: "text-dark-gray" %>
  <%= f.select :category,
    [[t('views.calendar.event'), "event"], [t('views.calendar.work_study'), "work_study"],[t('views.calendar.relax'), "relax"]],
    { prompt: t('views.calendar.select') }, class: "bg-matcha/65 text-beige py-2 pl-3 pr-10 rounded w-full focus:ring-2 focus:ring-matcha"
  %>

  <%= f.label :visibility, t('activerecord.attributes.calendar.visibility'), class: "text-dark-gray" %>
  <%= f.select :visibility,
    [[t('views.calendar.personal'), "personal"], [t('views.calendar.share_only'), "share_only"],[t('views.calendar.together'), "together"]],
    { prompt: t('views.calendar.select') }, class: "bg-matcha/65 text-beige py-2 pl-3 pr-10 rounded w-full focus:ring-2 focus:ring-matcha"
  %>
</div>
<div class="text-center">
  <%= f.submit t("buttons.save"), class: "bg-blue/75 text-dark-gray py-2 px-6 rounded hover:bg-blue/30 transition duration-200 mt-2", data: { turbo: false } %>
</div>

<script>
  document.addEventListener('DOMContentLoaded', function() {
    const timedRadio = document.querySelector('#schedule_type_timed');
    const allDayRadio = document.querySelector('#schedule_type_all_day');

    const timedFields = document.getElementById('timed-fields');
    const allDayFields = document.getElementById('all-day-fields');

    function toggleFields() {
      const isAllDay = allDayRadio.checked;

      timedFields.style.display = isAllDay ? 'none' : 'block';
      allDayFields.style.display = isAllDay ? 'block' : 'none';

      // 各 input を有効・無効化
      allDayFields.querySelectorAll('input').forEach(input => {
        input.disabled = !isAllDay;
      });
      timedFields.querySelectorAll('input').forEach(input => {
        input.disabled = isAllDay;
      });
    }

    timedRadio.addEventListener('change', toggleFields);
    allDayRadio.addEventListener('change', toggleFields);

    toggleFields(); // 初期化
  });
</script>

app/views/calendars/edit.html.erb
<%= link_to t("views.state_calendar.button"), room_calendars_path(@room), class: "bg-light-gray/75 p-4 rounded shadow mb-4" %>

<% @calendars.each do |calendar| %>

    <%= form_with model: [@room, calendar], local: true, class: "max-w-md mx-auto p-6 bg-light-gray/50 rounded-2xl shadow-lg mt-4" do |f| %>
        <% if calendar.errors.any? %>
            <div class="error-messages bg-red-100 text-red-700 p-4 mb-4 rounded">
            <ul class="list-disc pl-5">
                <% calendar.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
                <% end %>
            </ul>
            </div>
        <% end %>
        
        <%= render partial: "form", locals: { f: f } %>
        <%= link_to '<i class="fa-solid fa-trash text-lg text-blue"></i>'.html_safe, room_calendar_path(@room, calendar), data: { turbo_method: :delete, turbo_confirm: t("flash.alert")} %>
    <% end %>
<% end %>

<%= link_to t("buttons.back"), room_calendars_path(@room), class: "bg-light-gray/75 py-2 px-6 rounded shadow mb-4 hover:bg-light-gray/50 transition text-dark-gray mt-4" %>

app/views/calendars/index.html.erb
<div class="relative min-h-screen">
  <div class="container mx-auto px-4 py-8">
    <h1 class="text-matcha-green text-xl font-bold mt-6"><%= t('views.calendar.calendar_name', name: @room.name) %></h1>

    <%= button_to import_room_calendars_path(@room),
          method: :post,
          class: "flex items-center gap-2 bg-white border border-light-gray rounded-lg shadow-md px-4 py-2 text-dark-gray font-medium hover:bg-light_gray/30 transition",
          data: { turbo: false } do %>
      <%= image_tag '/Google_Calendar.png', alt: t('views.calendar.google_calendar'), width: 32, height: 32 %>
      <span><%= t('views.calendar.google_calendar') %></span>
    <% end %>
    <div class="text-sm">
      <%= t("views.calendar.notice_delete.one") %><br>
      <%= t("views.calendar.notice_delete.two") %><br>
      <%= t("views.calendar.notice_delete.three") %><br>
    </div>

    <div class="inline-block mt-6 mb-4 bg-matcha-green/20 p-2 rounded shadow-lg text-matcha font-bold hover:bg-brown/30 transition">
      <%= link_to t('views.calendar.private'), room_calendars_path(@room, visibility: 'personal'), class: "#{'text-matcha font-bold rounded bg-yellow' if params[:visibility] == 'personal'} whitespace-nowrap px-2" %>
    </div>

    <div class="mb-4 mt-6">
      <strong><%= t('views.calendar.category_filter') %>：</strong>
      <div class="underline">
        <%= link_to t('views.calendar.all'), room_calendars_path(@room), class: "mr-3 #{'text-matcha font-bold rounded bg-yellow' if params[:category].blank? && params[:visibility].blank? }" %>
        <%= link_to t('views.calendar.relax'), room_calendars_path(@room, category: 'relax'), class: "mr-3 #{'text-matcha font-bold rounded bg-yellow' if params[:category] == 'relax'}" %>
        <%= link_to t('views.calendar.work_study'), room_calendars_path(@room, category: 'work_study'), class: "mr-3 #{'text-matcha font-bold rounded bg-yellow' if params[:category] == 'work_study'}" %>
        <%= link_to t('views.calendar.event'), room_calendars_path(@room, category: 'event'), class: "mr-3 #{'text-matcha font-bold rounded bg-yellow' if params[:category] == 'event'}" %>
        <%= link_to t('views.calendar.together'), room_calendars_path(@room, visibility: 'together'), class: "#{'text-matcha font-bold rounded bg-yellow' if params[:visibility] == 'together'}" %>
      </div>
    </div>

    <%= month_calendar(events: @calendars, attribute: :calendar_date) do |date, plans_on_day| %>
      <% if current_user %>
        <% if plans_on_day.present? %>
          <% calendar = plans_on_day.find { |s| s.user_id == current_user.id } %>
          <% if calendar %>
            <%= link_to date.day, edit_room_calendar_path(@room, calendar, date: date), class: "block w-full h-full text-center", data: { turbo: false } %>
          <% else %>
            <%= link_to date.day, new_room_calendar_path(@room, date: date), class: "block w-full h-full text-center", data: { turbo: false } %>
          <% end %>
        <% else %>
          <%= link_to date.day, new_room_calendar_path(@room, date: date), class: "block w-full h-full text-center", data: { turbo: false } %>
        <% end %>
      <% else %>
        <span><%= date.day %></span>
      <% end %>

      <% plans_on_day.each do |plan| %>
        <% next unless plan.start_time.to_date == date %>

        <% if plan.user == current_user && plan.visibility != 'personal' && params[:visibility] == 'personal' %>
          <% next %>
        <% end %>

        <% css_class = case plan.category
          when "relax" then "bg-yellow"
          when "work_study" then "bg-pink-red/75"
          else "bg-matcha-green/50"
        end %>

        <% duration_days = (plan.end_time.to_date - plan.start_time.to_date).to_i + 1 %>

        <div class="text-xs leading-tight text-center">
          <% if plan.user == current_user %>
            <span class="inline-block px-0.5 py-0.5 rounded <%= css_class %>"><%= plan.name %></span>
          <% else %>
            <%= link_to room_calendar_path(@room, plan), class: "inline-block px-0.5 py-0.5 rounded #{css_class}" do %>
              <%= plan.name %>
            <% end %>
          <% end %>
          <% if plan.start_time.to_date != plan.end_time.to_date %>
            <div class="text-[10px] text-matcha">
              <%= l(plan.start_time.to_date, format: :short) %>-<%= l(plan.end_time.to_date, format: :short) %>（<%= "#{duration_days}日" %>）
            </div>
          <% end %>
            <span class="text-gray-600 text-[10px] block"><%= plan.user.name %></span>
        </div>
      <% end %>
    <% end %>
    <div class="text-center mt-8 mb-4">
      <%= link_to t("buttons.add_today"), new_room_calendar_path(@room), class: "bg-blue/75 p-4 rounded shadow mb-4 mt-2 hover:bg-blue-30 transition text-dark-gray", data: { turbo: false } %>
      <%= link_to t("views.room.back_to_room", room_name: @room.name), room_path(@room), class: "bg-brown/30 p-2 rounded shadow mb-2 mt-4 text-brown font-bold hover:bg-brown/70 transition", data: { turbo: false } %>
    </div>
  </div>
</div>

app/views/calendars/new.html.erb
<%= link_to t("views.state_calendar.button"), room_calendars_path(@room), class: "bg-light-gray/75 p-4 rounded shadow mb-4" %>

<%= form_with model: [@room, @calendar], local: true, class: "max-w-md mx-auto p-6 bg-light-gray/50 rounded-2xl shadow-lg mt-2" do |f| %>
  <% if @calendar.errors.any? %>
    <div class="error-messages bg-red-100 text-red-700 p-4 mb-4 rounded">
      <ul class="list-disc pl-5">
        <% @calendar.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= render partial: "form", locals: { f: f } %>
<% end %>

<%= link_to t("buttons.back"), room_calendars_path(@room), class: "bg-light-gray/75 py-2 px-6 rounded shadow mb-4 hover:bg-light-gray/50 transition text-dark-gray mt-4" %>

app/views/calendars/show.html.erb
<%= link_to t("views.state_calendar.button"), room_calendars_path(@room), class: "bg-light-gray/75 p-4 rounded shadow mb-4" %>

<div class="bg-light-gray/75 p-4 rounded shadow mb-4">

  <p class="text-dark-gray mb-2">
    <strong><%= t("activerecord.attributes.calendar.schedule_type") %>:</strong>
    <% if @calendar.start_time.to_date == @calendar.end_time.to_date %>
      <span class="inline-block px-2 py-1 rounded bg-yellow text-dark-gray">
        <%= t("views.calendar.all_day") %>：<%= @calendar.display_start_time %>
      </span>
    <% else %>
      <span class="inline-block px-2 py-1 rounded bg-yellow text-dark-gray">
        <%= t("views.calendar.start") %>：<%= @calendar.display_start_time %>
      </span>
      <span class="inline-block px-2 py-1 rounded bg-yellow text-dark-gray">
        <%= t("views.calendar.end") %>：<%= @calendar.display_end_time %>
      </span>
    <% end %>
  </p>

  <p class="text-dark-gray mb-2">
    <strong><%= t("activerecord.attributes.calendar.name") %>:</strong>
    <span class="inline-block px-2 py-1 rounded bg-light-blue/30 text-dark-gray">
      <%= @calendar.name %>
    </span>
  </p>
  
  <% if @calendar.description.present? %>
    <p class="text-dark-gray mb-2">
        <%= @calendar.description %>
    </p>
  <% else %>
    <h1><%= t("views.calendar.note") %></h1>
  <% end %>

  <div class="text-dark-gray mb-2">
    <ul class="list-disc pl-5 mt-2">
      <li><%= t("views.calendar.#{@calendar.visibility}")%></li>
      <li><%= t("views.calendar.#{@calendar.category}")%></li>
    </ul>
  </div>

</div>

<div class="flex justify-center">
  <%= link_to t("views.room.back_to_room", room_name: @room.name), room_path(@room), class: "bg-brown/30 p-2 rounded shadow mt-4 text-brown font-bold hover:bg-brown/70 transition" %>
</div>