config/routes.rb
Rails.application.routes.draw do
  get "users/show"
  get "rooms/index"
  get "exchange_diaries/index"

  devise_for :users, only: :omniauth_callbacks, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  scope "(:locale)", locale: /en|ja/ do
    devise_for :users, skip: :omniauth_callbacks, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
    }

    resource :user, only: %i[show]
    get "top/index"
    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
    resources :rooms, only: %i[index show create] do
      resources :exchange_diaries, only: %i[index create update destroy] do
        resource :read, only: %i[create destroy]
      end
      resources :whiteboards, only: %i[create update]
      resources :state_calendars, only: %i[new create index show update edit destroy]
      resources :invitation_tokens, only: %i[create index update]
      resources :greetings, only: %i[new create index edit update destroy]
      resources :spots, only: %i[index new create show edit update destroy] do
        resources :comments, only: %i[create update destroy]
      end
      resources :calendars, only: %i[index new create show edit update destroy] do
        collection do
          get :import
          post :import
        end
      end
    end

    resources :areas, only: %i[create update index]
    resources :weather_records, only: %i[create update]
    resources :posts, only: %i[new create index edit show update destroy] do
      resources :answers, only: %i[create edit destroy], shallow: true
    end
    resources :roommate_lists, only: %i[] do
      collection do
        get "join"  # /roommate_lists/join?token=xxx
      end
    end

    # Defines the root path route ("/")
    root "top#index"
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get "terms", to: "pages#terms", as: :terms
  get "privacy", to: "pages#privacy", as: :privacy
  get "contact", to: "pages#contact", as: :contact

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :exchange_diaries, dependent: :destroy
  has_many :whiteboards, dependent: :destroy
  has_many :state_calendars, dependent: :destroy
  has_many :roommate_lists, dependent: :destroy
  has_many :users, through: :roommate_lists
  has_many :roommates, through: :roommate_lists, source: :user
  has_many :invitation_tokens, dependent: :destroy
  has_many :greetings, dependent: :destroy
  has_many :spots, dependent: :destroy
  has_many :calendars, dependent: :destroy

  validates :name, presence: true, length: { maximum: 30 }
end

app/controllers/rooms_controller.rb
require "net/http"
require "uri"
require "json"

class RoomsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_room, only: [ :show ]
  before_action :authorize_room_access!, only: [ :show ]

  def index
    @room = Room.new
    invited_and_own_room
  end

  def create
    if current_user.owned_rooms.count >= 5
      flash[:alert] = t("flash.rooms.5rooms")
      redirect_to rooms_path and return
    end

    @room = current_user.owned_rooms.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: t("flash.rooms.new") }
      else
        invited_and_own_room
        flash.now[:alert] = t("flash.rooms.failed_create")
        format.html { render :index, status: :unprocessable_entity }
      end
    end
  end

  def show
    respond_to do |format|
      format.html
      format.json { render json: @room }
    end
    @whiteboards = @room.whiteboards.includes(:user).order(created_at: :desc)
    @whiteboard = @room.whiteboards.find_or_create_by(user: current_user)
    @roommates = User.joins(:roommate_lists).where(roommate_lists: { room_id: @room.id }).includes(area: :weather_record)

    @state_calendars = @room.state_calendars.includes(:user).order(created_at: :desc)
    @state_calendar = current_user.state_calendars.new
    @calendar_users = @state_calendars.includes(:user).map(&:user).uniq
    @greetings = @room.greetings.includes(:user).order(created_at: :desc)
    @welcome = @greetings.welcome
    @return = @greetings.return

    @my_welcome = @welcome.where(user: current_user)
    @others_welcome = @welcome.where.not(user: current_user)

    @my_return = @return.where(user: current_user)

    @roommates_except_self = current_user.roommates_except_self(@room)

    room_users = current_user.grouped_shared_users[@room.id]
    @calendar = Calendar
              .includes(:user)
              .where(room: @room, visibility: "together", user: room_users)
              .where("start_time >= ?", Date.today)
              .order(:start_time)
              .first

    @welcome_display =
      if @roommates_except_self.any?
        if @others_welcome.any?
          message = @others_welcome.sample
          { message: message.message, user: message.user }
        else
          user = @roommates_except_self.sample
          { message: t("flash.rooms.welcome"), user: user }
        end
      else
        if @my_welcome.any?
          message = @my_welcome.sample
          { message: message.message, user: message.user }
        else
          { message: t("flash.rooms.welcome"), user: current_user }
        end
      end

    @return_display =
      if @my_return.any?
        message = @my_return.sample
        { message: message.message, user: message.user }
      else
        { message: t("flash.rooms.return"), user: current_user }
      end

      if params[:from_home_button]
        users = (current_user.grouped_shared_users[@room.id] || [])
        updated_any = false
        failed_any = false

        users.uniq.each do |user|
          area = user.area
          next unless area

          weather_record = area.weather_record
          if weather_record.nil? || weather_record.updated_at < 30.minutes.ago
            weather_record ||= WeatherRecord.new(area: area)
            if save_weather_record(area, weather_record)
              updated_any = true
            else
              failed_any = true
            end
          end
        end

        if failed_any
          redirect_to root_path, alert: t("views.weather.failed_save") and return
        elsif updated_any
          redirect_to room_path(@room), notice: t("views.weather.update") and return
        else
          flash[:just_signed_in] = t("flash.rooms.back_home")
        end
      end
  end

  private

  def set_room
    @room = Room.find(params[:id])
  end

  def invited_and_own_room
    my_rooms = current_user.owned_rooms
    join_rooms = Room.joins(:invitation_tokens).where(invitation_tokens: { invited_user: current_user.id })
    @rooms = (my_rooms + join_rooms).uniq
    @invitation_map = InvitationToken
                      .where(invited_user: current_user, room_id: @rooms.map(&:id))
                      .index_by(&:room_id)
    @rooms = Room.where(id: @rooms.map(&:id)).includes(:user, :roommates)
    @area = current_user.area || current_user.build_area
  end

  def authorize_room_access!
    unless @room.user_id == current_user.id || RoommateList.exists?(user_id: current_user.id, room_id: @room.id)
      redirect_to root_path, alert: t("flash.rooms.none_access")
    end
  end

  def fetch_weather_from_api(city, lang = "ja")
    api_key = ENV["WEATHER_API"]
    url = URI("https://api.openweathermap.org/data/2.5/weather?q=#{city}&appid=#{api_key}&units=metric&lang=#{lang}")
    response = Net::HTTP.get_response(url)
    if response.is_a?(Net::HTTPSuccess)
      data = JSON.parse(response.body)
      Rails.logger.debug "API (#{lang}) description: #{data['weather'][0]['description']}"
      data
    else
      Rails.logger.error "API request failed: #{response.code} #{response.message}"
      nil
    end
  rescue => e
    Rails.logger.error "Weather API error: #{e.message}"
    nil
  end

  def save_weather_record(area, weather_record)
  ja_data = fetch_weather_from_api(area.city, "ja")
  en_data = fetch_weather_from_api(area.city, "en")

  return false unless ja_data.present? && en_data.present?

  weather_record.assign_attributes(
    temperature: ja_data["main"]["temp"],
    humidity: ja_data["main"]["humidity"],
    description: ja_data["weather"][0]["description"],
    description_en: en_data["weather"][0]["description"],
    temp_min: ja_data["main"]["temp_min"],
    temp_max: ja_data["main"]["temp_max"]
  )

  if weather_record.changed?
      weather_record.save
  else
      weather_record.touch
  end
  end

  def room_params
    params.require(:room).permit(:name)
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_area.html.erb
<div class="w-full max-w-md bg-white/30 rounded-xl shadow-lg p-4 max-h-[70vh] overflow-y-auto z-30">
  <div class="flex text-left mb-4">
    <i class="fa-solid fa-map-location-dot text-light-blue text-3xl lg:text-4xl"></i>
    <h1 class="text-sm lg:text-base font-bold mt-2">
      <%= t("views.area.register") %>
    </h1>
  </div>

  <%= form_with model: @area, local: true do |f| %>
    <div class="mb-3">
      <%= f.label :city, t('views.area.rule'), class: "block font-semibold mb-1 text-sm md:text-md lg:text-base" %>
      <%= f.text_field :city,
          placeholder: t('views.area.example'),
          class: "w-full p-2 rounded border bg-light-gray text-matcha text-sm font-bold md:text-md lg:text-lg" %>
    </div>

    <div class="text-center">
      <%= f.submit t('buttons.update'),
          class: "bg-light-blue text-dark-gray px-3 py-1.5 text-sm md:text-md lg:text-lg rounded hover:bg-light-blue/80 transition" %>
    </div>
  <% end %>
</div>

app/views/rooms/_board.html.erb
<div class="bg-white/65 shadow z-40 p-4 fixed top-[250px] left-4 w-[150px] h-[200px] md:w-[350px] md:h-[300px] overflow-y-auto">
  <h1 class="text-sm md:text-base text-dark-gray"><%= t("views.message_board.board") %></h1>
  <% if @whiteboards.empty? %>
    <p class="text-dark-gray text-center text-sm"><%= t("views.message_board.no_message") %></p>
  <% else %>
    <% @whiteboards.each do |board| %>
      <div class="mb-4 border-b border-gray-200 pb-2 text-sm text-dark-gray md:text-md">
        <% if board.user == current_user %>
            <div
                data-controller="board"
                data-board-room-id-value="<%= @room.id %>"
                data-board-target="board"
                data-action="keydown->board#insertBreak input->board#save"
                contenteditable="true"
                class="whitespace-pre-wrap focus:outline-none min-h-[40px]"
            >
            <%= h(board.body || "") %>
            </div>
        <% else %>
          <%= board.body %>
        <% end %>
        <div class= "flex text-matcha font-bold" >
          <h1><%= board.user.name %></h1>
          (<%= board.updated_at.strftime('%y/%m/%d %H:%M') %>)
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/rooms/_calendar.html.erb
<div class="fixed top-[400px] right-0 z-40 bg-white/50 p-4 rounded-lg shadow-md justify-end">
  <button id="calendar-button" class="text-3xl">
    <i class="fa-regular fa-calendar-days text-blue"></i>
  </button>
</div>

<div class="fixed top-[450px] right-0 z-40 p-4 flex justify-end">
  <div
    id="calendar-wrapper"
    class="hidden inline-block max-w-[30%] w-full cursor-pointer rounded shadow-lg hover:ring-2 hover:ring-blue transition"
    data-url="<%= room_state_calendars_path(@room) %>"
  >
    <%= week_calendar(events: @state_calendars, attribute: :calendar_date) do |date, states_on_day| %>
      <% states_on_day.each do |state| %>
        <p><%= state.mental_state %></p>
        <p><%= state.physical_state %></p>
      <% end %>
    <% end %>
  </div>
</div>

<script>
  document.addEventListener("DOMContentLoaded", function () {
    const wrapper = document.getElementById("calendar-wrapper");
    const button = document.getElementById("calendar-button");

    if (wrapper) {
      wrapper.addEventListener("click", function () {
        const url = wrapper.dataset.url;
        if (url) window.location.href = url;
      });
    }

    if (button && wrapper) {
      button.addEventListener("click", function (e) {
        e.preventDefault();
        wrapper.classList.toggle("hidden");
      });
    }
  });
</script>

app/views/rooms/_form.html.erb
<%= form_with model: @room, url: rooms_path, remote: true do |f| %>
  <% if @room.errors.any? %>
    <div class= "text-bold text-brown">
        <% @room.errors.full_messages.each do |message| %>
          <ul>
            <li><%= message %></li>
          </ul>
        <% end %>
    </div>
  <% end %> 
  <div class="bg-light-gray/75 p-4 rounded shadow mb-4">
    <%= f.label :name, "家の名前", class: "text-sm text-dark-gray" %>
    <%= f.text_field :name, placeholder: "新しい家の名前を追加してください", class: "bg-light-gray w-full p-2 border rounded text-gray" %>
    <div class="flex justify-center">
      <%= f.submit "登録", class: "bg-light-blue text-dark-gray px-4 py-2 mt-2 rounded hover:bg-light-blue/80 transition" %>
    </div>
  </div>
<% end %>

app/views/rooms/_form_area.html.erb
<%= form_with(model: @area,  local: true ) do |f| %>
  <div class="bg-light-gray/75 p-4 rounded shadow mb-4">
    <%= f.label :city, t('views.area.rule'), class: "text-sm text-dark-gray" %>
    <%= f.text_field :city, placeholder: t('views.area.example'), class: "bg-light-gray w-full p-2 border rounded text-gray" %>
    <div class="flex justify-center">
      <%= f.submit t("buttons.register^"), class: "bg-light-blue text-dark-gray px-4 py-2 mt-2 rounded hover:bg-light-blue/80 transition" %>
    </div>
    <div class="text-gray text-right">*いずれもあとで変更可</div>
  </div>
<% end %>

app/views/rooms/_form_board.html.erb
<div class="bg-white shadow z-40 p-4 fixed top-[220px] right-4 w-[150px] h-[260px] overflow-y-auto">
  <div
    data-controller="board"
    data-board-room-id-value="<%= @room.id %>"
    data-board-target="board"
    data-action="keydown->board#insertBreak input->board#save"
    contenteditable="true"
    class="min-h-[200px] whitespace-pre-wrap focus:outline-none"
  >
  <%= h(@whiteboard&.body || "") %>
  </div>

  <% if @whiteboard.present? %>
    <div class="text-sm text-gray-600 border-t border-gray-200 pt-2">
      <p class="text-matcha">
        <span class="<%= @whiteboard.user == current_user ? 'text-gray-800 font-semibold' : '' %>">
          <%= @whiteboard.user.name %>（<%= @whiteboard.updated_at.strftime('%Y/%m/%d %H:%M') %>）
        </span>
      </p>
    </div>
  <% end %>
</div>

app/views/rooms/_greeting.html.erb
<% if flash[:just_signed_in] %>
  <div id="login-greeting">
  <div class="fixed top-[580px] md:top-[600px] left-0 z-40 justify-end text-beige md:text-black">
    <p><%= @welcome_display[:user].name %></p>
    <p class="bg-blue/50 p-4 rounded-lg shadow-md"><%= @welcome_display[:message] %></p>
  </div>

  <div class="fixed top-[500px] md:top-[520px] left-0 z-40 justify-end text-beige md:text-black">
    <p><%= @return_display[:user].name %></p>
    <p class="bg-matcha/50 p-4 rounded-lg shadow-md"><%= @return_display[:message] %></p>
  </div>
</div>

<script>
  setTimeout(() => {
    const box = document.getElementById('login-greeting');
    if (box) {
      box.style.transition = 'opacity 1s ease';
      box.style.opacity = 0;
      setTimeout(() => box.remove(), 1000);
    }
  }, 30000);
</script>

<% end %>

app/views/rooms/_weather.html.erb
<% if @roommates.present? %>
  <div class="fixed top-[80px] md:top-[75px] left-0 z-40 bg-white/65 rounded-lg md:p-2 shadow-md">
  <% @roommates.each do |user| %>
    <div class="weather flex text-sm md:text-lg md:space-x-2 border border-light-gray rounded">
      <h3><%= user.name %></h3>
      <% if user.area.nil? %>
        <p><%= t("views.area.advice") %></p>
      <% else %>
        <p><i class="fa-solid fa-location-pin text-red-500"></i> <%= user.area.city %></p>

        <% weather_record = user.area.weather_record %>

        <% if weather_record.nil? %>
          <%= button_to t('buttons.get'), weather_records_path(area_id: user.area.id, room_id: @room.id), method: :post, data: { turbo: false } %>
        <% else %>
          <% desc = I18n.locale == :en ? weather_record.try(:description_en) || weather_record.description : weather_record.description %>
          <% color_class =
            if desc.include?("晴") || desc.include?("Clear")
              "text-orange-500/75 font-bold"
            elsif desc.include?("雨") || desc.include?("Rain")
              "text-matcha font-bold"
            else
              "text-gray font-bold"
            end
          %>
          <p class="<%= color_class %>"><%= I18n.locale == :ja ? weather_record.description : weather_record.description_en %></p>
          <p class="<%= color_class %>"><%= weather_record.temperature %>℃</p>
          <% if weather_record.created_at == weather_record.updated_at %>
            <p><i class="fa-solid fa-clock text-matcha-green/75"></i> <%= weather_record.created_at.strftime('%m/%d %H:%M') %></p>
          <% else %>
            <p><i class="fa-solid fa-clock text-matcha-green/75"></i> <%= weather_record.updated_at.strftime('%m/%d %H:%M') %></p>
          <% end %>
          <%= button_to t('buttons.update'), weather_record_path(weather_record, area_id: user.area.id, room_id: @room.id), method: :patch, data: { turbo: false }, class: "text-blue underline font-bold" %>
        <% end %>
      <% end %>
      <%= render "status", user: user %>
    </div>
  <% end %>
  </div>
<% else %>
  <div class="fixed top-[80px] md:top-[75px] left-0 z-40 bg-white/75 rounded-lg shadow-md">
    <div class="weather flex space-x-2 text-sm md:text-lg px-2 py-1 border border-light-gray rounded">
    <h3><%= current_user.name %></h3>
    <% if current_user.area.nil? %>
      <p><%= t("views.area.advice") %></p>
    <% else %>
      <p><i class="fa-solid fa-location-pin text-red-500"></i> <%= current_user.area.city %></p>

      <% weather_record = current_user.area.weather_record %>

      <% if weather_record.nil? %>
          <%= button_to t('buttons.get'), weather_records_path(area_id: user.area.id, room_id: @room.id), method: :post, data: { turbo: false } %>
        <% else %>
          <% color_class =
            if weather_record.description.include?("晴")
              "text-orange-500 font-bold"
            elsif weather_record.description.include?("曇") || weather_record.description.include?("雨") || weather_record.description.include?("雲")
              "text-matcha font-bold"
            else
              "text-gray-700 font-bold"
            end
          %>
          <p class="<%= color_class %>"><%= I18n.locale == :ja ? weather_record.description : weather_record.description_en %></p>
          <p class="<%= color_class %>"><%= weather_record.temperature %>℃</p>
          <% if weather_record.created_at == weather_record.updated_at %>
            <p><i class="fa-solid fa-clock text-matcha-green/75"></i> <%= weather_record.created_at.strftime('%m/%d %H:%M') %></p>
          <% else %>
            <p><i class="fa-solid fa-clock text-matcha-green/75"></i> <%= weather_record.updated_at.strftime('%m/%d %H:%M') %></p>
          <% end %>
          <%= button_to t('buttons.update'), 
          weather_record_path(
            weather_record,
            area_id: (defined?(user) ? user.area.id : current_user.area.id),
            room_id: @room.id
          ),
          method: :patch,
          data: { turbo: false },
          class: "text-blue underline font-bold" %>
      <% end %>
    <% end %>
    <%= render "status", user: current_user %>
    </div>
  </div>
<% end %>

app/views/rooms/show.html.erb
<% content_for :main_class, "relative w-full flex flex-col mt-0" %>
<div class="fixed top-[25px] md:top-[60px] left-1/2 transform -translate-x-1/2 z-30 p-4">
  <div class="text-matcha text-center text-md md:text-2xl font-bold rounded-lg shadow-md p-2">
    <%= @room.name %><i class="fa-solid fa-house-user"></i>
  </div>
</div>
<%= render 'weather' %>
<%= render 'board' %>

<% if @room.user_id == current_user.id %>
  <div class="group relative">
    <%= link_to room_invitation_tokens_path(@room),
        class: "fixed top-[200px] md:top-[100px] right-4 z-30 flex items-center justify-center w-14 h-14 rounded-full shadow-lg bg-matcha-green hover:bg-matcha hover:scale-110 transition-transform duration-300",
        data: { turbo: false, label: t('views.room_show.invitation') },
        href: room_invitation_tokens_path(@room) do %>
      <i class="fa-solid fa-user-plus text-2xl transition-transform duration-300 group-hover:rotate-[12deg]"></i>
    <% end %>

    <span class="fixed top-[200px] md:top-[100px] right-4 -translate-y-1/2
                opacity-0 md:opacity-0 md:group-hover:opacity-100
                bg-beige text-xs md:text-sm rounded px-2 py-1 shadow
                transition-opacity duration-300 whitespace-nowrap z-30 pointer-events-none">
      <%= t('views.room_show.invitation') %>
    </span>
  </div>
<% end %>

<!--%= render 'calendar' %>-->


<%= render 'greeting' %>
<div class="group relative">
  <%= link_to room_exchange_diaries_path(@room),
      class: "fixed top-[250px] md:top-[150px] right-4 z-30 flex items-center justify-center w-14 h-14 rounded-full shadow-lg bg-beige hover:bg-blue-600 hover:scale-110 transition-transform duration-300",
      id: "open-book",
      data: { room_path: room_exchange_diaries_path(@room), turbo: false, label: t('views.room_show.diary') },
      href: room_exchange_diaries_path(@room) do %>
    <i class="fa-solid fa-book-open text-2xl transition-transform duration-300 group-hover:rotate-[12deg]"></i>
  <% end %>

  <span class="fixed top-[250px] md:top-[150px] right-4 -translate-y-1/2
               opacity-0 md:opacity-0 md:group-hover:opacity-100
               bg-beige text-xs md:text-sm rounded px-2 py-1 shadow
               transition-opacity duration-300 whitespace-nowrap z-30 pointer-events-none">
    <%= t('views.room_show.diary') %>
  </span>
</div>

<div class="group relative">
  <%= link_to room_spots_path(@room),
      class: "fixed top-[300px] md:top-[200px] right-4 z-30 flex items-center justify-center w-14 h-14 rounded-full shadow-lg bg-beige hover:bg-blue-600 hover:scale-110 transition-transform duration-300",
      id: "open-door",
      data: { room_path: room_spots_path(@room), turbo: false, label: t('views.room_show.place') },
      href: room_spots_path(@room) do %>
    <i class="fa-solid fa-map-pin text-2xl transition-transform duration-300 group-hover:rotate-[12deg]"></i>
  <% end %>

  <span class="fixed top-[300px] md:top-[200px] right-4 -translate-y-1/2
               opacity-0 md:opacity-0 md:group-hover:opacity-100
               bg-beige text-xs md:text-sm rounded px-2 py-1 shadow
               transition-opacity duration-300 whitespace-nowrap z-30 pointer-events-none">
    <%= t('views.room_show.place') %>
  </span>
</div>

<div class="group relative">
  <%= link_to room_state_calendars_path(@room),
      class: "fixed top-[350px] md:top-[250px] right-4 z-30 flex items-center justify-center w-14 h-14 rounded-full shadow-lg bg-beige hover:bg-blue-600 hover:scale-110 transition-transform duration-300",
      data: { turbo: false, label: t('views.room_show.state') },
      href: room_state_calendars_path(@room) do %>
    <i class="fa-solid fa-briefcase-medical text-2xl transition-transform duration-300 group-hover:rotate-[12deg]"></i>
  <% end %>

  <span class="fixed top-[350px] md:top-[250px] right-4 -translate-y-1/2
               opacity-0 md:opacity-0 md:group-hover:opacity-100
               bg-beige text-xs md:text-sm rounded px-2 py-1 shadow
               transition-opacity duration-300 whitespace-nowrap z-30 pointer-events-none">
    <%= t('views.room_show.state') %>
  </span>
</div>

<div class="group relative">
  <%= link_to room_calendars_path(@room),
      class: "fixed top-[400px] md:top-[300px] right-4 z-30 flex items-center justify-center w-14 h-14 rounded-full shadow-lg bg-beige hover:bg-blue-600 hover:scale-110 transition-transform duration-300",
      data: { turbo: false, label: t('views.room_show.calendar') },
      href: room_calendars_path(@room) do %>
    <i class="fa-solid fa-calendar text-2xl transition-transform duration-300 group-hover:rotate-[12deg]"></i>
  <% end %>

  <span class="fixed top-[400px] md:top-[300px] right-4 -translate-y-1/2
               opacity-0 md:opacity-0 md:group-hover:opacity-100
               bg-beige text-xs md:text-sm rounded px-2 py-1 shadow
               transition-opacity duration-300 whitespace-nowrap z-30 pointer-events-none">
    <%= t('views.room_show.calendar') %>
  </span>
</div>

<div class="group relative">
  <%= link_to room_greetings_path(@room),
      class: "fixed top-[450px] md:top-[350px] right-4 z-30 flex items-center justify-center w-14 h-14 rounded-full shadow-lg bg-matcha-green hover:bg-matcha hover:scale-110 transition-transform duration-300",
      data: { turbo: false, label: t('views.room_show.message') },
      href: room_greetings_path(@room) do %>
    <i class="fa-solid fa-comment text-2xl transition-transform duration-300 group-hover:rotate-[12deg]"></i>
  <% end %>

  <span class="fixed top-[450px] md:top-[350px] right-4 -translate-y-1/2
               opacity-0 md:opacity-0 md:group-hover:opacity-100
               bg-beige text-xs md:text-sm rounded px-2 py-1 shadow
               transition-opacity duration-300 whitespace-nowrap z-30 pointer-events-none">
    <%= t('views.room_show.message') %>
  </span>
</div>

<div class="absolute bottom-20 lg:bottom-32 right-0 z-30 bg-white/80 p-4 rounded-lg shadow-md text-matcha text-xs md:text-lg font-bold text-right max-w-xs">
  <% if current_user.calendars.exists?(visibility: 'together') && @calendar.present? %>
      <%= t("views.calendar.share_calendar") %> <br>
      <%= link_to @calendar.name, room_calendars_path(@room), class: "calendar-link" %><br>
      <% if @calendar.start_time.beginning_of_day == @calendar.start_time && @calendar.end_time.end_of_day == @calendar.end_time %>
        <%= l(@calendar.start_time.to_date, format: :long) %>
      <% else %>
        <%= l(@calendar.start_time, format: :long) %> ～ <%= l(@calendar.end_time, format: :long) %>
      <% end %>
  <% else %>
    <%= t("views.calendar.no_share_calendar") %>
  <% end %>
</div>

<% if mobile_device? %>
  <%= image_tag '/gif.gif' %>
<% else %>
  <%= render 'home' %>
  <div id="loading-screen" style="position:absolute; top:0; left:0; width:100%; height:100%; background:yellow/30; z-index:10; display:flex; align-items:center; justify-content:center; pointer-events:none;">
    <div class="text-center text-matcha text-2xl animate-bounce font-bold">
      <%= t('views.room_show.cleaning') %>...🧹
    </div>
  </div>
<% end %>

<script>
  document.addEventListener("DOMContentLoaded", () => {
    if (window.innerWidth < 768) {
      document.querySelectorAll('.group > a[data-label]').forEach(btn => {
        const label = btn.nextElementSibling;
        btn.addEventListener('click', (e) => {
          if (!label.classList.contains('opacity-100')) {
            e.preventDefault(); // 1回目クリックで遷移キャンセル
            label.classList.remove('opacity-0');
            label.classList.add('opacity-100');
          }
          // 2回目クリックでリンク遷移
        });
      });
    }
  });
</script>